#!/bin/bash
#
#
# rc.single     This file is executed by init when it goes into runlevel
#               1, which is the administrative state. It kills all
#               deamons and then puts the system into single user mode.
#               Note that the file systems are kept mounted.
#
# Author:       Miquel van Smoorenburg, <miquels@drinkel.nl.mugnet.org>
#               Modified for RHS Linux by Damien Neil
#               Modified for FOG by Chuck Syperski
#
/usr/bin/psplash-write "MSG Getting Ready..."
ln -s /proc/self/fd /dev/fd
ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr
if [[ $mdraid == true ]]; then
    mdadm --assemble --scan
    mdadm --incremental --run --scan
fi
[[ -n $keymap ]] && loadkeys $keymap
/usr/bin/psplash-write "MSG Contacting FOG Server..."
/usr/bin/psplash-write "PROGRESS 80"

/usr/bin/psplash-write "MSG Starting FOS..."
/usr/bin/psplash-write "PROGRESS 90"
appURL="http://google.com"
startx &
sleep 10
/usr/bin/psplash-write "QUIT"
