#!/bin/sh

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
/usr/bin/psplash &
/usr/bin/psplash-write "PROGRESS 20"
/usr/bin/psplash-write "MSG Preparing FOG"
for i in /etc/init.d/S??* ; do
    [[ ! -f $i ]] && continue
    case "$i" in
        *.sh)
            # Source shell script for speed
            (
            trap - INT QUIT TSTP
            set start
            . $i
            )
            ;;
        *)
            # No sh extension, so fork subprocess.
            $i start
            ;;
    esac
done
