#!/bin/bash
#
# Start logging
#

start() {
    printf "Starting logging: "
    /usr/bin/psplash-write "MSG Starting Logging..."
    /usr/bin/psplash-write "PROGRESS 30"
    start-stop-daemon -b -S -q -m -p /var/run/syslogd.pid --exec /sbin/syslogd -- -n
    start-stop-daemon -b -S -q -m -p /var/run/klogd.pid --exec /sbin/klogd -- -n
    echo "OK"
    /usr/bin/psplash-write "MSG Started Logging..."
    /usr/bin/psplash-write "PROGRESS 30"
}

stop() {
    printf "Stopping logging: "
    start-stop-daemon -K -q -p /var/run/syslogd.pid
    start-stop-daemon -K -q -p /var/run/klogd.pid
    echo "OK"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
