#!/bin/sh
#
# run gdk-pixbuf-query-loaders if needed

FILE=/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache

case "$1" in
    start|"")
        if [[ ! -f $FILE ]]; then
            /usr/bin/psplash-write "MSG Starting Graphics..."
            /usr/bin/psplash-write "PROGRESS 60"
            /usr/bin/gdk-pixbuf-query-loaders --update-cache
            /usr/bin/psplash-write "MSG Started Graphics"
            /usr/bin/psplash-write "PROGRESS 60"
        fi
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 {start|stop}" >&2
        exit 1
        ;;
esac
