#!/bin/bash
#
# Assertion harness for FOS's md RAID auto-assembly gate.
#
#   tests/checks/mdraid-gate.sh        # check the overlay
#   tests/checks/mdraid-gate.sh -b     # also diff against the built upstream rule
#
# Why this exists. FOS assembles md arrays only when the kernel command line
# carries mdraid=true (etc/init.d/S99fog). But Buildroot's mdadm package
# installs mdadm's udev rules whenever eudev is the device manager, and
# 64-md-raid-assembly.rules runs "mdadm --incremental" on every RAID member at
# coldplug. So arrays assembled anyway, held their member partitions, and a
# capture of those partitions failed (forums topic 18202). The reporter's
# workaround was a postinit script that deleted the rule and stopped every
# array.
#
# The fix masks the rule with a gated copy in /etc/udev/rules.d. This check
# asserts that the mask exists, that the gate comes before any rule that can
# reach mdadm, and that S99fog releases arrays when mdraid is off. With -b it
# also proves the copy below the gate still matches the rule mdadm installs,
# so an mdadm bump cannot leave a stale copy behind.

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$HERE/../.."
OVERLAY="$ROOT/Buildroot/board/FOG/FOS/rootfs_overlay"
RULE="$OVERLAY/etc/udev/rules.d/64-md-raid-assembly.rules"
S99="$OVERLAY/etc/init.d/S99fog"

build=0
[[ $1 == -b ]] && build=1

fails=0
fail() { echo "FAIL: $*"; fails=$((fails + 1)); }
pass() { echo "  ok  $*"; }

# 1. The mask exists, with the name that shadows mdadm's /lib file.
if [[ ! -f $RULE ]]; then
    fail "no $RULE -- mdadm's rule assembles arrays without mdraid=true"
    exit 1
fi
pass "overlay masks 64-md-raid-assembly.rules"

# 2. The first two rule lines (comments and blanks skipped) are the gate.
mapfile -t rules < <(grep -v -e '^[[:space:]]*#' -e '^[[:space:]]*$' "$RULE")
if [[ ${rules[0]} == 'IMPORT{cmdline}="mdraid"' &&
      ${rules[1]} == 'ENV{mdraid}!="true", GOTO="md_inc_end"' ]]; then
    pass "gate on mdraid=true precedes every other rule"
else
    fail "the first rules are not the mdraid gate:"
    printf '       %s\n' "${rules[0]}" "${rules[1]}"
fi

# 3. The gate jumps to a label that exists, or udev ignores the GOTO.
if grep -qx 'LABEL="md_inc_end"' "$RULE"; then
    pass "gate target LABEL=\"md_inc_end\" exists"
else
    fail "gate target LABEL=\"md_inc_end\" is missing"
fi

# 4. S99fog stops kernel-autodetected arrays when mdraid is off.
if awk '/^if \[\[ \$mdraid == true \]\]/{f=1} f&&/^else/{e=1} e&&/mdadm --stop --scan/{s=1} /^fi/{if(f)exit} END{exit !s}' "$S99"; then
    pass "S99fog stops arrays when mdraid is not true"
else
    fail "S99fog has no 'mdadm --stop --scan' in the mdraid-off branch"
fi

# 5. Optional: the copy below the gate matches what mdadm installs.
if [[ $build -eq 1 ]]; then
    found=0
    for upstream in "$ROOT"/fssource*/output/target/lib/udev/rules.d/64-md-raid-assembly.rules; do
        [[ -f $upstream ]] || continue
        found=1
        # Drop the FOG header and gate: everything before upstream's first line.
        if diff -u "$upstream" <(sed -n '/^# do not edit this file/,$p' "$RULE") >/dev/null; then
            pass "copy matches $(realpath --relative-to="$ROOT" "$upstream")"
        else
            fail "copy differs from $upstream -- re-copy it below the gate"
            diff -u "$upstream" <(sed -n '/^# do not edit this file/,$p' "$RULE") | sed 's/^/       /'
        fi
    done
    [[ $found -eq 0 ]] && echo "  --  -b: no built fssource*/ tree, upstream comparison skipped"
fi

echo
if [[ $fails -eq 0 ]]; then
    echo "PASS: md auto-assembly follows mdraid=true"
else
    echo "FAILED: $fails check(s)"
    exit 1
fi
